#!/usr/bin/env bash
# Step 6 — regenerate the human-readable report from analysis/insights.json.
# Run: bash analysis/tools/gen-report.sh
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
IN="$ROOT/analysis/insights.json"
OUT="$ROOT/analysis/INSIGHTS-REPORT.md"

{
echo "# Build4Venezuela — Repository Insights Report"
echo ""
echo "Automated analysis of project GitHub repositories: tech stack, architecture, production-readiness, real-problem fit, and diffusion (promo) readiness."
echo ""
echo "- **$(jq length "$IN")** repositories analyzed. Re-generated by \`analysis/tools/gen-report.sh\`."
echo ""
echo "## 1. Recommendation tiers"
echo ""
for reco in spotlight promote merge-candidate improve-first deprioritize; do
  n=$(jq --arg r "$reco" '[.[]|select(.evaluation.overall_recommendation==$r)]|length' "$IN")
  [ "$n" -eq 0 ] && continue
  echo "### $reco ($n)"
  echo ""
  jq -r --arg r "$reco" '
    [.[]|select(.evaluation.overall_recommendation==$r)]
    | sort_by([-(.analysis.viability.score), -(.evaluation.product_quality)])
    | .[]
    | "- **\(.project_slug)** — _\(.evaluation.one_line_pitch)_\n  - viability \(.analysis.viability.score)/5 · prod-ready \(.analysis.production_readiness.score)/5 · product \(.evaluation.product_quality)/5 · diffusion \(.evaluation.diffusion.score)/5 · demo: \(.evaluation.live_demo_status) · severity: \(.evaluation.problem_severity)\n  - repo: \(.repo_url) · live: \(.live_url)"
  ' "$IN"
  echo ""
done

echo "## 2. Diffusion-ready shortlist"
echo ""
jq -r '
  [.[]|select(.evaluation.diffusion.ready_to_promote==true and (.evaluation.live_demo_status=="working" or .video_url!=""))]
  | sort_by(-(.evaluation.diffusion.score)) | .[]
  | "- **\(.project_slug)** (diffusion \(.evaluation.diffusion.score)/5) — assets: \(.evaluation.diffusion.available_assets|join(", "))\n  - angle: \(.evaluation.diffusion.recommended_angle)"
' "$IN"
echo ""

echo "## 3. Overlap map (projects per domain)"
echo ""
jq -r '[.[] | . as $p | .analysis.domain_tags[] | {tag:., slug:$p.project_slug}] | group_by(.tag) | sort_by(-length) | .[] | "- **\(.[0].tag)** (\(length)): \([.[].slug]|join(", "))"' "$IN"
echo ""

echo "## 4. Per-project detail"
echo ""
jq -r '
  sort_by(.project_slug) | .[]
  | "### \(.project_slug)\n"
  + "\(.analysis.summary)\n\n"
  + "- **Type:** \(.analysis.project_type)\n"
  + "- **Stack:** FE: \(.analysis.stack.frontend|join(", ")) | BE: \(.analysis.stack.backend|join(", ")) | DB: \(.analysis.stack.database|join(", ")) | AI: \(.analysis.stack.ai_ml|join(", "))\n"
  + "- **Architecture:** \(.analysis.architecture.pattern) · ORM: \(.analysis.architecture.uses_orm) (\(.analysis.architecture.orm_or_db_layer)) · API: \(.analysis.architecture.api_design)\n"
  + "- **Scores:** maturity \(.analysis.maturity.score)/5 · prod-ready \(.analysis.production_readiness.score)/5 · org \(.analysis.code_organization.score)/5 · viability \(.analysis.viability.score)/5 · product \(.evaluation.product_quality)/5 · diffusion \(.evaluation.diffusion.score)/5\n"
  + "- **Signals:** \(.signals.stars // 0)★ · \(.signals.commit_count // 0) commits · \(.signals.code_loc // 0) LOC · \(.signals.contributors // 0) contributors · \(.signals.license // "no-license")\n"
  + "- **Real problem:** \(.evaluation.solves_real_problem) (\(.evaluation.problem_severity)) — \(.evaluation.real_problem_reasoning)\n"
  + "- **Live demo:** \(.evaluation.live_demo_status) — \(.evaluation.live_demo_notes)\n"
  + "- **Recommendation:** \(.evaluation.overall_recommendation)\n"
  + "- **Red flags:** \(.analysis.red_flags|join("; "))\n"
  + "- **Merge potential:** \(.analysis.merge_potential)\n"
' "$IN"
} > "$OUT"
echo "wrote $OUT ($(wc -l < "$OUT") lines)"
